apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    type: web
spec:
  replicas: 3
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      labels:
        type: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
