apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
  labels:
    type: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    type: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs2
spec:
  selector:
    matchLabels:
      type: nginx 
  serviceName: "nginx-headless-service"
  replicas: 3 
  template:
    metadata:
      labels:
        type: nginx 
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /var/www/
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi