apiVersion: batch/v1
kind: Job
metadata:
  name: job2
spec:
  ttlSecondsAfterFinished: 10
  completions: 5
  template:
    metadata:
      name: consumer
    spec:
      containers:
      - name: consumer
        image: busybox
        command: ["/bin/sh","-c"]
        args: ["echo 'consuming a message'; sleep 5"]
      restartPolicy: OnFailure