apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - nodePort: 31080
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  volumes:
  - name: jenkins-volume
    hostPath:
        path: /home/jenkins
        
  containers:
  - name: my-jenkins
    image: pratik977/my_jenkins:1.0
    volumeMounts:
    - mountPath: ~/.jenkins
      name: jenkins-volume
      
    ports:
      - containerPort: 8080
