apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs2
spec:
  replicas: 5
  selector:
    matchExpressions:
    - key: type
      operator: In
      values: [web, webserver]
  template:
    metadata:
      labels:
        type: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
