apiVersion: v1
kind: Pod
metadata:
  name: initpod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo 'I am the main container!' && sleep 3600"]
  initContainers:
  - name: init-1
    image: busybox
    command: ['sh', '-c', 'sleep 50']

  - name: init-2
    image: busybox
    command: ['sh', '-c', "echo 'I am in init-2'"]