apiVersion: v1
kind: Pod 
metadata:
  name: pod3
  labels:
    image: busybox

spec:               
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - ls
    