apiVersion: v1
kind: Pod 
metadata:
  name: pod4
  labels:
    image: busybox
    count: '3'

spec:
  containers:
  - name: busybox1
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    args:
    - -c
    - "echo 'This is container1'; sleep 3600"
  
  - name: busybox2
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    args:
    - -c
    - "echo 'This is container2'; sleep 3600"
  
  - name: busybox3
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    args:
    - -c
    - "echo 'This is container3'; sleep 3600"