apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    type: webserver
    image: nginx
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.17.4
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
