apiVersion: v1
kind: Pod
metadata:
  name: pod5
  labels:
    image: busybox
spec:
  restartPolicy: Never
  volumes:
  - name: shared-volume
    emptyDir: {}

  containers:
  - name: box1
    image: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: shared-volume
      mountPath: /home
    command:
    - /bin/sh
    args:
    - -c
    - "echo 'Content from box1'>/home/file.txt"

  - name: box2
    image: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: shared-volume
      mountPath: /home
    command: 
    - /bin/sh
    args: 
    - -c
    - "cat /home/file.txt"