apiVersion: v1
kind: Pod
metadata:
  name: pod6
  labels:
    type: web

spec:
  containers:
  - name: frontend
    image: pratik977/demo_app:1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
  - name: db
    image: redis:alpine
    imagePullPolicy: IfNotPresent