apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    image: nginx
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx:latest
   
  - name: alpine
    image: alpine
